// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import "./globals.css";
// import Nav from "./components/Nav";

// export const metadata = {
//   title: "Motorsågskörkortet",
//   description: "Lär dig om motorsågskörkort.",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="sv">
//       <body>
//         <Nav />
//         <div>{children}</div>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Nav from "./components/Nav";
import FooterComponent from "./components/FooterComponent";

export const metadata = {
  title: "Motorsågskörkortet",
  description: "Lär dig om motorsågskörkort.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sv">
      <body className="min-h-screen flex flex-col">
        <Nav />
        <main className="flex-grow">{children}</main>
        <FooterComponent />
      </body>
    </html>
  );
}
